export const GET_ALL_PRODUCTS_ACTION = "CATALOG::GET_ALL_PRODUCTS_ACTION"
export const GET_ALL_CATEGORIES_ACTION = "CATALOG::GET_ALL_CATEGORIES_ACTION"
export const SET_PRODUCT_CATEGORY_ACTION = "CATALOG::SET_PRODUCT_CATEGORY_ACTION"